create table public.users
(
    id           bigint       not null
        primary key,
    account_type varchar(255) not null
        constraint users_accounttype_check
            check ((accounttype)::text = ANY
        ((ARRAY ['APPLICANT'::character varying, 'RECRUITER'::character varying])::text[])),
    email        varchar(255) not null
        constraint uk6dotkott2kjsp8vw4d0m25fb7
            unique,
    name         varchar(255) not null,
    password     varchar(255) not null
);

alter table public.users
    owner to postgres;

create table public.jobs
(
    id             bigint generated by default as identity,
    company        varchar(255),
    description    varchar(255),
    jobstatus      varchar(255)
        constraint jobs_jobstatus_check
            check ((jobstatus)::text = ANY
        ((ARRAY ['OPEN'::character varying, 'CLOSED'::character varying, 'DRAFT'::character varying])::text[])),
    jobtype        varchar(255),
    location       varchar(255),
    packageoffered bigint,
    posttime       timestamp(6),
    title          varchar(255)
);

alter table public.jobs
    owner to postgres;

create table public.applicants
(
    applicantid bigint generated by default as identity
        primary key,
    status      varchar(255)
        constraint applicants_status_check
            check ((status)::text = ANY
        ((ARRAY ['APPLIED'::character varying, 'REVIEWED'::character varying, 'INTERVIEWING'::character varying, 'OFFERED'::character varying])::text[])),
    timestamp   timestamp(6),
    job_id      bigint not null
);

alter table public.applicants
    owner to postgres;

create table public.job_skillsrequired
(
    job_id         bigint not null,
    skillsrequired varchar(255)
);

alter table public.job_skillsrequired
    owner to postgres;

